### ISSUE TITLE
Add link for user to change password and configure 2FA

### ISSUE THREAD

**Issue by stefan-karg** [cryptomator/hub#187]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/hub/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/hub/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Enable a non-admin user to change the password and configure 2FA

### Motivation

Currently, the only option is to trigger a password change and to configure 2FA in keycloak by an admin. This should be possible as a self-service for each user. The link to the corresponding user account page (https://login1.cryptomator.cloud/realms/[tenant]/account/) should be accessible via the menu on the top right.

### Considered Alternatives

None.

**Comment by tobihagemann** [comment]
Thank you for your suggestion! We're currently creating a profile page, where this link would fit. The commit b6cdc625cda027c94e154c0d0ca3a4eaf4b9ce55 would fix this issue but I guess we still have to move around some code so that it will actually make it into a near-future update release. 😄 Just wanted to mention it so that you know that this is coming!

**Comment by stefan-karg** [comment]
Thanks a lot for the update, @tobihagemann !
