### ISSUE TITLE
Native Image doesn't contain `curl`

### ISSUE THREAD

**Issue by tobihagemann** [cryptomator/hub#249]
The native image of Hub (with `-amd64` suffix) doesn't contain `curl`. This prevents an easy way to perform health checks, as shown in our own Setup Wizard.

I must admit that I didn't check this myself. This information is based on third-party feedback.

**Comment by overheadhunter** [comment]
I would like to keep the image small, as it is very simple to extend an image in order to add further software.

**Comment by SailReal** [comment]
> https://github.com/cryptomator/hub/commit/b2a79c1dc9a3cb3ff606e080ae9bc28f162592de

Just verified it, yes, `curl` isn't included in the native image. Interestingly that they keep it in the non-native image :thinking: .

We've already added `curl` to the Keycloak image so that the Docker Compose health check running in the container will work for Keycloak https://github.com/cryptomator/hub/commit/b2a79c1dc9a3cb3ff606e080ae9bc28f162592de but as our Hub default image for Docker Compose is not the native image, I would also vote for not including it so that we have the security benefits of not having something that can do random web requests in the image but maybe we should document it somewhere.

**Comment by tobihagemann** [comment]
All right, thank you for both of your input. So this is basically working as intended. I'm not sure, we even documented the existence of native images anywhere. If we did, we could document the missing `curl`, but that's an issue for another repo.
