### ISSUE TITLE
After upgrade 1.2.2 -> 1.3.3, archived vault can't be unarchived

### ISSUE THREAD

**Issue by stefan-karg** [cryptomator/hub#269]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/hub/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/hub/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

After upgrade 1.2.2 -> 1.3.3, archived vault can't be unarchived

### System Setup

```markdown
- Hub: 1.3.3 (before was: 1.2.2)
- Keycloak: 23.0.7
- Cryptomator (Desktop/Android/iOS): independent
```

### Steps to Reproduce

1. [Running on Hub version 1.2.2]
2. Archive a vault
3. [Upgrade to Hub version 1.3.3]
4. Claim ownership of archived vault with vault password
5. Click on vault to manage it

### Expected Behavior

Vault management UI is shown with possibility to unarchive vault.

### Actual Behavior

Vault management UI is shown as if I would not be owner of the vault (see screenshot)
![Screenshot 2024-04-11 145835](https://github.com/cryptomator/hub/assets/1040937/3fb7695b-d8e9-4e61-9875-11e62d196be8)

### Reproducibility

Always

**Comment by SailReal** [comment]
Thanks for reporting this bug.

During `grantOwnership` we post from the client (frontend) the new user key based [access token to the backend](https://github.com/cryptomator/hub/blob/develop/frontend/src/components/VaultDetails.vue#L325), but this request fails because the [resource checks if the vault is archived](https://github.com/cryptomator/hub/blob/develop/backend/src/main/java/org/cryptomator/hub/api/VaultResource.java#L345-L347). 

![image](https://github.com/cryptomator/hub/assets/1786772/7275ad5f-b5a0-4666-9123-81e1014ff7ac)

The problem now is that this vault has been migrated, but the access token hasn't been saved. That's why the UI doesn't give you the option to unarchive this vault.

We can verify this by setting the archived flag to false by accessing the database, then the frontend will show

![image](https://github.com/cryptomator/hub/assets/1786772/0b673c80-4a55-4bec-8b4e-2da99e73edcc)

We can now enter the recovery key for this vault to regain access to it. We can then archive the vault again.

We will be fixing this bug soon.
